Fix variable type
WebChemistry/images pull request #46
Opened 2020-03-13 12:19 UTC by krekos

Fix compatibility with Nette/Image

2020-03-16 10:17 UTC, krekos commented
FIX of the same thing but on the side of Nette/images.

https://github.com/nette/utils/pull/217

2020-03-30 09:23 UTC, MartkCz requested changes

2020-03-30 09:23 UTC, MartkCz commented on src/Storages/LocalStorage.php
> +			} catch (ImageException $e){
`$e){` to `$e) {`

2020-03-30 09:23 UTC, MartkCz commented on src/Modifiers/BaseModifiers.php
> +		$height = is_string($height) && substr($height, -1) !== '%' ? (int)$height : $height;
`(int)$var` to `(int) $var`

2020-03-30 09:23 UTC, MartkCz commented on src/Modifiers/BaseModifiers.php
> +			$height = is_string($height) && substr($height, -1) !== '%' ? (int)$height : $height;
`(int)$var` to `(int) $var`

2020-03-30 09:59 UTC, merged